modLoader           = "javafml"
loaderVersion = "[36.0,)"
license = "https://github.com/splatcraft/splatcraft-forge/blob/HEAD/LICENSE"

[[mods]]
modId           = "splatcraft"
displayName     = "Splatcraft"
description     = '''
        Splatcraft is a Minecraft mod based on Nintendo's popular game Splatoon!
        This mod aims to add items and mechanics based on the game in a cohesive way, such as Turf Wars, Weapons, Squid Transformations and many more!
    '''
authors = "Cibernet, L1ttle, Andante"
credits = "Thanks to Nintendo and Mojang, for making such great games!"
logoFile = "pack.png"

version = "${file.jarVersion}"
# updateJSONURL   = "https://splatcraft.net/data/update/splatcraft.json"

displayURL = "https://curseforge.com/minecraft/mc-mods/splatcraft"
issueTrackerURL = "https://github.com/splatcraft/splatcraft-forge/issues"

[[dependencies.splatcraft]]
modId           = "forge"
mandatory = true
versionRange = "[36.2.20,)"
ordering = "NONE"
side            = "BOTH"
[[dependencies.splatcraft]]
modId           = "obfuscate"
mandatory = true
versionRange = "[0.6.3,)"
ordering = "NONE"
side            = "CLIENT"
[[dependencies.splatcraft]]
modId           = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side            = "BOTH"
