modLoader           = "javafml"
loaderVersion       = "[34,)"
license             = "https://github.com/splatcraft/splatcraft/blob/HEAD/LICENSE"

[[mods]]
modId           = "splatcraft"
displayName     = "Splatcraft"
description     = '''
        Splatcraft is a Minecraft mod based on Nintendo's popular game Splatoon!
        This mod aims to add items and mechanics based on the game in a cohesive way, such as Turf Wars, Weapons, Squid Transformations and many more!
    '''
authors         = "Cibernet, Andante"
credits         = "Thanks to Nintendo and Mojang, for making such great games!"
logoFile        = "pack.png"

version         = "${file.jarVersion}"
# updateJSONURL   = "https://splatcraft.net/data/update/splatcraft.json"

displayURL      = "https://curseforge.com/minecraft/mc-mods/splatcraft"
issueTrackerURL = "https://github.com/splatcraft/splatcraft/issues"

[[dependencies.splatcraft]]
modId           = "forge"
mandatory       = true
versionRange    = "[34.0,)"
ordering        = "NONE"
side            = "BOTH"
[[dependencies.splatcraft]]
modId           = "minecraft"
mandatory       = true
versionRange    = "[1.16.3,)"
ordering        = "NONE"
side            = "BOTH"
